#!/bin/bash

set -e

INPUT_DIR=raw
OUTPUT_DIR=converted
TMP_VIDEO_FILE=/tmp/video.mp4
RESOLUTION=656:370
MENCODER_OPTS="-nosound -ovc xvid -vf yadif,scale=$RESOLUTION -xvidencopts bitrate=1000:chroma_opt:vhq=4:bvhq=1:quant_type=mpeg:max_bframes=1:threads=4"
OUTPUT_FILE=${OUTPUT_DIR}/$(echo $(basename $1) | sed 's/_/ /g' | sed 's/ [^ ]\{8\} default.mp4$/.mp4/')

if [ ! -d 'converted' ]; then mkdir converted; fi

mencoder $1 -o /dev/null $MENCODER_OPTS:pass=1

mencoder $1 -o $TMP_VIDEO_FILE $MENCODER_OPTS:pass=2

ffmpeg -i $TMP_VIDEO_FILE -i $1 -map 0:0 -map 1:1 -vcodec copy -acodec copy "$OUTPUT_FILE"
